FROM ubuntu:xenial
RUN apt update
RUN apt-get install -y arpwatch net-tools vim nano tcpdump
RUN apt-get install -y \
    git \
    net-tools \
    aptitude \
    build-essential \
    python-setuptools \
    python-dev \
    python3-pip \
    software-properties-common \
    ansible \
    curl \
    iptables \
    iputils-ping \
    sudo \
    bridge-utils 

